index:
  pattern:   /index
  defaults:  { _controller: AcmeIndexBundle:Index:index }

login:
  pattern:   /login
  defaults:  { _controller: AcmeAuthBundle:Auth:login }

reg:
  pattern:   /reg
  defaults:  { _controller: AcmeAuthBundle:Auth:reg }

recovery_email:
  pattern:   /recovery
  defaults:  { _controller: AcmeAuthBundle:Auth:recovery }

secure_index:
  pattern:   /secure/index
  defaults:  { _controller: AcmeSecureBundle:Secure:index }

secure_talk:
  pattern:   /secure/talk
  defaults:  { _controller: AcmeSecureBundle:Secure:talk }

secure_schedule:
  pattern:   /secure/schedule/{mode}
  defaults:  { _controller: AcmeSecureBundle:Secure:schedule, mode: empty }

unauthorized:
  pattern:  /unauthorized
  defaults: { _controller: AcmeAuthBundle:Auth:unauthorized }

logout:
  pattern:  /logout
  defaults: { _controller: AcmeAuthBundle:Auth:logout }

confirm_password:
  pattern:   /auth/confirm
  defaults:  { _controller: AcmeAuthBundle:Auth:confirm }


secure_download_file:
  pattern:   /download/{type}/{num}/{filename}
  defaults:  { _controller: AcmeSecureBundle:Secure:downloadFile, filename: empty  }

secure_upload:
  pattern:   /secure/author/upload
  defaults:  { _controller: AcmeSecureBundle:Secure:upload }
